### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [Andrew-Chen-Wang/django-async-redis#1]
There are still several things remaining before this can be made into a stable package:

 - [ ] BIG ISSUE: after I last committed and finished studying, I realized that I was passing around the client object,  Redis not ContextRedis, around and that would continuously open up new connections. Aioredis creator named this a blocking operation, and I used it mostly because pytest would actually work and I believe that was better than using the shared connections. The problem is, take `async def set` in the `DefaultClient`: we're using several connections at a time rather than one connection because we're passing `client` and not `c`. The current solution is linked in the next comment.
 - [x] Test if Django 2.2 also works. It probably does, but I can only imagine Django channels users using it... and only using it for only their websockets portion.
 - [ ] Different clients and different modes. I've currently only implemented 1 client, the DefaultClient. django-redis has HerdClient and ShardedClient
 - [ ] Better documentation. I'm so bad at documentation lmao. Just look at django-cachalot and you'll notice how wonky I am at configuration. At some point, I'll make it that nice table of contents RTD theme (forgot its name)
 - [x] Different compressors and serializers. Currently I've only implemented JSON and Picker serializer (not msgpack) and the IdentitityCompressor as that was the only one that seemed to work for async (based on docs; never tested).
 - [ ] I'm not sure what a HashRing is made specifically for... that'll just have to wait lmao.
 - [x] All additional aioredis commands which can be found here: https://aioredis.readthedocs.io/en/v1.3.0/mixins.html
 - [x] Edit the README so that people working with async have an easier time. Additionally, I've posted on Reddit a simple example of how to get type annotations as I haven't filed a ticked for Django to include those async methods in `BaseCache`. Although, I'd much rather have people use `django_async_redis.cache.RedisCache` since we could be adding A LOT more methods with the aioredis command mixins.

I'm going to need help with this, so please do consider making some PRs. I've got midterms for the next two weeks, so lots of GOOD (not shitoberfest quality) contributions would be helpful!

Cheers,
Andrew

**Comment by Andrew-Chen-Wang** [comment]
For the big issue, the solution is to do it the semi-old fashioned way, i.e. intermixing `__enter__` and `__exit__` magic methods with the old way of `try...finally`:

```
    async def touch(
        self, key, timeout=DEFAULT_TIMEOUT, version=None, client: Redis = None
    ):
        """
        Sets a new expiration for a key.
        """

        if timeout is DEFAULT_TIMEOUT:
            timeout = self._backend.default_timeout

        existent = False
        if hasattr(client, "__enter__") and hasattr(client, "__exit__"):
            existent = True
            c = client
        elif client is None:
            client = await self.get_client(write=True)
            c = (await client).__enter__()
        else:
            raise NotImplementedError("You must implement __enter__ and __exit__ for your client.")

        try:
            key = self.make_key(key, version=version)
            if timeout is None:
                return bool(await c.persist(key))
            else:
                # Convert to milliseconds
                timeout = int(timeout * 1000)
                return bool(await c.pexpire(key, timeout))
        finally:
            if not existent:
                c.__exit__()
```
Unfortunately, this may not be foolproof. I'm seeing some edge cases which might require me to use pytest parametrization to actually see that all combos are working as expected (i.e. only one connection is actually opened).

**Comment by Andrew-Chen-Wang** [comment]
Before I go on a week long hiatus, a different solution is to have all calls to redis in a private function:

```python
async def _set(client: ContextRedis, *args, **kwargs):
    await c.set(*args, **kwargs)

async def set(*args, **kwargs):
     with await client as c:
         await _set(client: c, *args, **kwargs)
```

**Comment by Andrew-Chen-Wang** [comment]
closing issue as we're now using redis-py
